"""Initial migration

Revision ID: 127a22f85a9a
Revises: 
Create Date: 2026-01-08 12:00:37.137682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127a22f85a9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
